### ISSUE TITLE
Подписку перенести в компонент, разнести логику для грида и хайчарта в разные сервисы

### ISSUE THREAD

**Issue by Ternovskiy** [n19z/highchart-AgGrid#1]
https://github.com/n19z/highchart-AgGrid/blob/46153f3d51983a4b8513a5437a41c11aeb4df181/src/app/services/data.service.ts#L37

**Comment by n19z** [comment]
Закрывать ишью, которые вроде исправил?  или вы сами можете закрыть их:D
