### ISSUE TITLE
а это для чего?

### ISSUE THREAD

**Issue by DbrmnPhrh** [n19z/highchart-AgGrid#10]
https://github.com/n19z/highchart-AgGrid/blob/46153f3d51983a4b8513a5437a41c11aeb4df181/src/app/services/data.service.ts#L9

И ещё интерфейс лучше вынести в отдельный файл i-coordinate

**Comment by n19z** [comment]
Сначала думал, что понадобятся айдишники, потом забыл убрать. Для интерфейсов приемлемо использовать отдельные папки? Например "interfaces"

**Comment by DbrmnPhrh** [comment]
Ну обычно структура папки с компоннетом у нас такая:
![image](https://user-images.githubusercontent.com/15796191/136027598-57728eb9-9142-41f9-92fb-847ec863c1e4.png)
1 папка с компонентом
2 дочерние компоненты
3 сервис используемый компонентом
4 файл с интерфейсами

просто если будет какая-то глобальная для проекта папка с интерфейсами со временем их наберётся очень много и сложно будет искать или удалять, например, если удаляется какой-то компонент использующий этот интерфейс

**Comment by n19z** [comment]
Интересно. Хорошо, идею понял, спасибо. Сервисы и интерфейс перенесу
